# Generated by Django 5.2.1 on 2025-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa'), ('Excluída', 'Excluída')], default='Ativa', max_length=20),
        ),
    ]
