# Generated by Django 5.2.1 on 2025-11-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='RelatorioMensal',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
